services:
  arthuria-bot:
    container_name: arthuria_bot
    image: ghcr.io/yokainfromabyss/arthuria-bot:main
    restart: always
    volumes:
    # This is path to full config folder. You need to create all required files before starting container.
      - /path/to/config.yaml:/app/resources/config.yaml:ro
    depends_on:
      - arthuria-db

  arthuria-db:
    container_name: arthuria-db
    image: postgres:12.18-alpine3.19
    restart: always
    volumes:
      # Path to persist postgresql data over time. Use bind mount or volume as needed.
      - /path/to/database:/var/lib/postgresql/data
      # This path is needed only for first start to populate db with required tables. Can be deleted afterwards.
      - /path/to/sqlinit.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
